reverting a wrong change

diff --git a/ashlib b/ashlib
--- a/ashlib
+++ b/ashlib
@@ -13,137 +13,45 @@
 #    You should have received a copy of the GNU General Public License
 #    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 #
-#*#####################################################################
-## This is a implicit module automatically invoked by:
-##
-##    eval $(ashlib)
-##
-## The `core` module is included automatically.
-#*####################################################################
+#++
+# = ASHLIB(1)
+# :Revision:	1.0
+# :Author:	A Liu Ly
+# :man manual:  ashlib programmer's manual
+#
+# == NAME
+#
+# ashlib - set-up shell environment to use ashlib
+#
+# == SYNOPSIS
+#
+# eval $(ashlib)
+#
+# == DESCRIPTION
+#
+# Set the running shell process so that in can import *ashlib* modules
+# easily.
+#
+#--
+set -euf -o pipefail
 
-find_in_path() {
-  ##   Find a file in a path
-  ## # USAGE
-  ##   find_in_path [--path=PATH] file
-  ## # OPTIONS
-  ## * --path=PATH : don't use $PATH but the provided PATH
-  ## # DESC
-  ## Find a file in the provided path or PATH environment
-  ## variable.
-  ## # RETURNS
-  ## 0 if found, 1 if not found
-  ## # OUTPUT
-  ## full path of found file
-  ##
-  local spath="$PATH"
-  while [ $# -gt 0 ]
+if [ -z "${ASHLIB:-}" ] ; then
+  # Figure the location of the ashlib library
+  script_dir=$(cd $(dirname $0) ; pwd)
+  ASHLIB=""
+  for target in . ../lib ../lib/ashlib ../ashlib
   do
-    case "$1" in
-    --path=*)
-      spath="${1#--path=}"
-      ;;
-    *)
+    if [ -f $script_dir/$target/ashlib.sh ] ; then
+      ASHLIB="$(cd $script_dir/$target ; pwd)"
       break
-      ;;
-    esac
-    shift
+    fi
   done
-  if [ x"${1:0:1}" = x"/" ] ; then
-    [ -f "$1" ] && echo "$1" && return 0
-    return 1
+  if [ -z "$ASHLIB" ] ; then
+    echo "Unable to determine ASHLIB location" 1>&2
+    exit 1
   fi
-  local d oIFS="$IFS" ; IFS=":"
-  for d in $spath
-  do
-    if [ -f "$d/$1" ] ; then
-      echo "$d/$1"
-      IFS="$oIFS"
-      return 0
-    fi
-  done
-  IFS="$oIFS"
-  return 1
-}
+  echo "export ASHLIB=$ASHLIB;"
+fi
+echo "source \$ASHLIB/ashlib.sh"
 
 
-ifind_in_path() {
-    ## Determines if the specified file is in the path variable
-    ## # USAGE
-    ##   ifind_in_path needle haystack_variable
-    ## # ARGS
-    ## * needle -- item to find in the path variable
-    ## * haystack_variable -- name of the variable contining path
-    ## # RETURNS
-    ## 0 if found, 1 if not found
-    ## # OUTPUT
-    ## full path of found file
-    local cmd="$1"
-    local dirs="$(eval echo \$$2 | tr ':' ' ')"
-    local dd
-    for dd in $dirs
-    do
-      if [ -e $dd/$cmd ] ; then
-	echo $dd/$cmd
-	return 0
-      fi
-    done
-    return 1
-}
-
-include() {
-  ## Include an `ashlib` module.
-  ## # USAGE
-  ##   include [--once] module [other modules ...]
-  ## # ARGS
-  ## * --once|-1 : if specified, modules will not be included more than once
-  ## * module -- module to include
-  ## # RETURNS
-  ## 0 on success, otherwise the number of failed modules.
-  [ -z "${ASHLIB_PATH:-}" ] && export ASHLIB_PATH="${ASHLIB:-.}"
-
-  local once=false
-
-  while [ $# -gt 0 ]
-  do
-    case "$1" in
-    --once|-1)
-      once=true
-      ;;
-    *)
-      break
-      ;;
-    esac
-    shift
-  done
-
-  local ext fn i c=0
-  for i in "$@"
-  do
-    for ext in ".sh" ""
-    do
-      if fn=$(find_in_path --path="$ASHLIB_PATH" $i$ext) ; then
-	if $once ; then
-	  # Make sure this fn has not been included before...
-	  if (echo "${_included_once_file_list:-}" | grep -q '^'"$fn"'$') ; then
-	    # OK, included before...
-	    continue 2
-	  fi
-	  # remember that we found it before...
-	  if [ -z "${_included_once_file_list:-}" ] ; then
-	    _included_once_file_list="$fn"
-	  else
-	    _included_once_file_list="$(echo "$_included_once_file_list"; echo "$fn")"
-	  fi
-	fi
-	. $fn
-	break
-      fi
-    done
-    if [ -z "$fn" ] ; then
-      echo "$i: not found" 1>&2
-      c=$(expr $c + 1)
-    fi
-  done
-  return $c
-}
-include core
